#
# JBZoo Toolbox - Composer-Diff.
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @see        https://github.com/JBZoo/Composer-Diff
#

name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'
  schedule:
    - cron: '39 */8 * * *'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  phpunit-build:
    name: PHPUnit (build)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4, 8.0, 8.1 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        run: make build --no-print-directory

      - name: 🧪 PHPUnit Tests
        run: make test --no-print-directory

      - name: Uploading coverage to coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make report-coveralls --no-print-directory || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PHPUnit (build) - ${{ matrix.php-version }} - ${{ matrix.coverage }} - ${{ matrix.build-way }}
          path: build/
